public ip - 3.36.115.25
private ip - 10.0.0.226



name: Github Actions 을 이용하여 배포하기

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
  DEPLOY_PATH: /var/www/html

jobs:
  code-fetch-job:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 가져오기
      - name: checkout source
        uses: actions/checkout@v4

      - name: Folder-permission
        uses: appleboy/scp-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_PRIVATE_KEY }}
          script: |
            sudo chown -R ${{ env.EC2_USERNAME }}:${{ env.EC2_USERNAME }} ${{ env.DEPLOY_PATH }}
            sudo chmod -R 755 ${{env.DEPLOY_PATH}}
      # 2. EC2에 접속하여 스크립트 실행
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_PRIVATE_KEY }}
          source: "index.html"
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 0
