name: Github Actions 을 이용하여 배포하기

on:
  push:
    branches:
      - main

jobs:
  deployment-job:
    runs-on: ubuntu-latest

    steps:
      - name: secret-variables-check
        run: |
          echo ${{ secrets.EC2_USER }} >> ec2_user.txt
          echo ${{ secrets.EC2_PEM_KEY }} >> ec2_pem_key.txt
          cat ec2_pem_key.txt
